# deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: moderation-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moderation
  template:
    metadata:
      # identifier of pod going to be created
      labels:
        app: moderation
    spec:
      containers:
        - name: moderation
          image: debjitroy86/moderation
---
# cluster IP service
apiVersion: v1
kind: Service
metadata:
  name: moderation-srv
spec:
  selector:
    app: moderation
  type: ClusterIP
  ports:
    - name: moderation
      protocol: TCP
      port: 4004
      targetPort: 4004
