apiVersion: v1
kind: Service
metadata:
  name: posts-srv
spec:
  type: NodePort
  # find all the pods with identifier app: posts (see posts-depl)
  selector:
    app: posts
  ports:
    - name: posts
      protocol: TCP
      port: 4000
      targetPort: 4000
